### ISSUE TITLE
Explore sorting mediastack results by relevance

### ISSUE THREAD

**Issue by markertmer** [stevenjames-turing/consultancy_news_BE#28]
On a number of searches, we are getting some rather unrelated articles. I think this is happening because we chose to get the most recent matching article, even if it's not the most relevant. 

We might want to take another look at the Mediastack API query options and see if there might be a way we can pull more relevant articles.

**Comment by stevenjames-turing** [comment]
Unfortunately, the only way we have to control the content of the articles is through the keyword param. I think the solution to this would be to either use more specific or longer search terms. 

I think there is a technical solution, but it would require us to create multiple article summaries, count the number of times certain words appear within the summary and then return summaries with a similar word count as the others (or something along those lines.)

If you're ok with it, I'm going to close this issue as un-resolved.
